repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: requirements-txt-fixer
-   repo: https://github.com/PyCQA/flake8.git
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ['--config', '.flake8']
