version: '3'

services:
  odoo:
    image: odoo:15.0
    container_name: odoo_cnt
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
    expose:
      - 8069
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo

  db:
    image: postgres:13
    container_name: db_cnt
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - ./odoo_postgres:/var/lib/postgresql/data/pgdata

  nginx-server:
    build: ./nginx
    container_name: nginx_cnt
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
    depends_on:
      - odoo

    external_links:
      - odoo
      - db
