version: '3'

services:
  odoo:
    image: odoo:15.0
    user: root
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8099:8069"
      - "8071:8071"
      - "8072:8072"
    volumes:
      - ./data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo

  db:
    image: postgres:13
    env_file:
      - .env.postgres
    expose:
      - 5432
    volumes:
    - ./odoo_postgres:/var/lib/postgresql/data/pgdata
