version: 2.1


jobs:

  linting-test:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Build docker
          command: docker-compose up --build -d
